- .github/workflows/docs.yml
- .github/workflows/main.yml
Neovim 0.10.4 changed the name of the Linux binary in their releases,
which was breaking the github actions worflow.
> Changed the name of the linux binary in github actions

- .github/workflows/docs.yml
There is no GH_PAT configured in the secrets for this new repo. Changed
the variable to GITHUB_TOKEN to check if it has enough permissions, if
it doesn't we will need to create a PAT and add it to the repo secrets.
> Trying to fix github actions when merging to main

- CHANGELOG.md
- README.md
- lua/obsidian/client.lua
doc: remove some verbose description in plugin dependencies
> doc: add instruction for rocks.nvim, warning for packer.nvim

- CHANGELOG.md
- README.md
- doc/obsidian.txt
- lua/obsidian/util.lua
PR for ticket https://github.com/obsidian-nvim/obsidian.nvim/issues/35.
When your cursor is on a tag
you can press enter (default mapping) to open the tag picker and see all notes with that tag
> feat: `smart_action` shows tag picker when cursor is on a tag

- lua/obsidian/completion/plugin_initializers/blink.lua
There's a warning while using the latest version of blink saying that blink.add_provider is deprecated and will be removed with version 1.0.0 and to use blink.add_source_provider instead. 
This PR makes that update.
> Fix: blink.add_provider is deprecated - use add_source_provider instead

- lua/obsidian/client.lua
If your templates folder is configured as e. g. 'Templates' and you happen to have a folder of the same name in `$CWD`, this should guard against picking the wrong folder.
I for instance have a folder 'Templates' in my home directory, which is completely unrelated to obsidian. When I start nvim while `$CWD == $HOME`, this folder would be used for obsidian templates instead, which is completely unexpected. In this case, when creating a new daily note for instance, I would get an error message telling me that the daily template could not be found.
Why you ever would want to search for obsidian templates outside your vault I don't understand, so I kept that logic there instead of removing it, but at least I think it should happen as a last resort, not as an override.
This PR simply …
> Search for templates folder in vault_root first

- .github/workflows/docs.yml
- CHANGELOG.md
- Makefile
- it is self documenting: just call `make` to see all targets
- it gets missing dependencies
Now the output of `make` looks like this:
If you don't have deps, like `mini.doc`, it clones it automatically:
> feat: makefile is friendlier

- CHANGELOG.md
- lua/obsidian/commands/init.lua
- lua/obsidian/commands/toggle_checkbox.lua
Modified the toggle_checkbox command implementation so that it works in visual mode as well.
It allows to toggle the checkbox on multiple lines. 
Also added a check to avoid the toggle on empty lines.
> ObsidianToggleCheckbox works in visual mode multiline (#56)

- CHANGELOG.md
- after/ftplugin/markdown.lua
- after/syntax/markdown.vim
Quite a easy one to implement, no block comment because neovim don't support for now.
It looks far better then the inline html comment for me.
Let me know if people like this! 
@ffricken @sotte @TheMeaningfulEngineer
> feat: support obsidian style %% comment

- CHANGELOG.md
- lua/obsidian/commands/rename.lua
The rename command does not replace the id in the frontmatter with the new name.
Moreover I have noticed that although there was code to delete the old buffer (with the old name) it was not working because saveas() associates the old bufnr to the new buffer and creates an new one for the old and it unloads the old buffer. 
I simplified and fixed the code so the old buffer gets deleted correctly
No issues are directly associated in this repo but it fixes an issue from the original one.
- Issue gathering interesting original repo issues (#74) 
- https://github.com/epwalsh/obsidian.nvim/issues/688 from original repo
> bugfix: rename does not replace id nor delete old buffer if in current note

- CHANGELOG.md
- README.md
- doc/obsidian.txt
- lua/obsidian/commands/dailies.lua
- lua/obsidian/commands/init-legacy.lua
- lua/obsidian/commands/init.lua
- lua/obsidian/commands/rename.lua
- lua/obsidian/config.lua
- lua/obsidian/init.lua
- lua/obsidian/mappings.lua
- lua/obsidian/util.lua
This "namespaces" all of the commands as discussed [here](https://github.com/obsidian-nvim/obsidian.nvim/discussions/6#discussioncomment-12363874).
I accidentally closed the old PR, this is the one from before but with some changes to the command registering and it adds an option to enable all of the old commands.
> refactor(Commands): Merge all commands into one :Obsidian command

- CHANGELOG.md
- README.md
- lua/obsidian/init.lua
- lua/obsidian/util.lua
Since pressing `<Enter>` on headings don't make sense, this extends the idea of a smart action that does the most intuitive things pretty well I think.
Also neovim ships with markdown treesitter parser now, it works even if you don't have nvim-treesitter.
@sotte let me know what you think
> feat: smart action can toggle heading folds

- .all-contributorsrc
- README.md
1. moved the extra docs beyond configuration options to the [Wiki](https://github.com/obsidian-nvim/obsidian.nvim/wiki).
2. used the native github alert syntax for warning.
3. folded the configuration options.
4. bumped the minimal required version to 0.10 #59 
5. remove TOC because the file is short enough.
resolves #19 
TODO:
> Readme cleanup

- CHANGELOG.md
- README.md
- lua/obsidian/client.lua
- lua/obsidian/config.lua
- lua/obsidian/init.lua
If you use lualine: 
```lua
{
"nvim-lualine/lualine.nvim",
opts = {
sections = {
lualine_x = {
"g:obsidian",
},
},
},
},
```
the status is automatically updated through `vim.g.obsidian`
TODO:
> feat: add statusline component provider

- CHANGELOG.md
- lua/obsidian/completion/sources/base/refs.lua
- lua/obsidian/config.lua
This adds config option `completion.match_case`, which prevents the plugin from adding an additional completion entry when a match is found but with the wrong case. E.g. searching for `foo` when the note's file name is `FooBar.md`.
Closes #90
Changes to be committed:
- modified:   lua/obsidian/completion/sources/base/refs.lua
- modified:   lua/obsidian/config.lua
- modified:   lua/obsidian/util.lua
> feat: Add config option to avoid duplicate completion items.

- CHANGELOG.md
- README.md
- lua/obsidian/commands/init-legacy.lua
- lua/obsidian/commands/init.lua
- lua/obsidian/commands/new_from_template.lua
I adjusted the implementation of the logic a bit.
The check for the `template_dir()` already happens in another place of the code. I removed the redundancy. 
(Note: this is an alternative version  of #34.)
(Side note: it's a bit annoying to maintain both new command and legacy commands.)
> feat(ObsidianNewFromTemplate): accept template argument

- CHANGELOG.md
- lua/obsidian/commands/init-legacy.lua
- lua/obsidian/commands/init.lua
With `complete=file`, Ex command evaluates substrings quoted by backticks in its args before the args are passed to their callback functions via `data`. This should not be an ideal behavior for `:ObsidianNew` and `ObsidianRename`, and `ObsidianPasteImg`.
Addition to that, the `complete=file` settings do not make sense because the commands do not expect unique ID of which filename is composed as arguments, but a title in natural language.
> fix(commands): drop complete=file

- README.md
This fixes a typo :smile: Thanks for maintaining obsidian.nvim!
> docs: fix follow_img_func typo

- CHANGELOG.md
- after/ftplugin/markdown.lua
- lua/obsidian/init.lua
- Placed in `ftplugin/markdown.lua` so that users can override it later.
- Remove settings for `fillchars`, `foldtext`, `foldlevel`, or `smoothscroll`, as these are not necessary for obsidian.nvim.
- Resolves [issue #136](https://github.com/obsidian-nvim/obsidian.nvim/issues/136)
> feat: configure `foldmethod` and `foldexpr` in ftplugin

- CHANGELOG.md
- lua/obsidian/config.lua
As per #81 and #154, we want to have a `backlinks` table added for future config options.
Specifically, `parse_headers` that I'm adding in #154.
> feat: add backlinks config module

- CHANGELOG.md
- README.md
- doc/obsidian.txt
- lua/obsidian/commands/backlinks.lua
- lua/obsidian/config.lua
By default, `ObsidianBacklinks` tries to parse header titles as links for look up.
This isn't desirable if 1) titles don't follow a structure that `ObsidianBacklinks` expects; 2) you just don't want it, and prefer to look up the current note, or wiki-link under the current cursor.
This PR just adds an extra config field to customise this behaviour.
N/A
> feat: toggle header parsing

- CHANGELOG.md
- lua/obsidian/client.lua
- lua/obsidian/init.lua
A draft to see what it feels like to have a autocmd system
Advantages:
1. allow any number of callbacks called from different places
2. no need to have callbacks in config
3. better for user scripting and other plugin to integrate.
Some very mature plugins in the community all supports this: 
https://github.com/nvim-telescope/telescope.nvim?tab=readme-ov-file#autocmds
https://github.com/OXY2DEV/markview.nvim?tab=readme-ov-file#-autocmds
> feat: user autocmd events instead of callback manager

- CHANGELOG.md
- README.md
- lua/obsidian/config.lua
- lua/obsidian/ui.lua
In https://github.com/epwalsh/obsidian.nvim/issues/286#issuecomment-2048334358 it was suggested that a new config could be added to specifically not warn if the conceal level is 0 and the UI is enabled.
This commit does this and guard against the conceal warning when the option is set.
cc https://github.com/epwalsh/obsidian.nvim/issues/492
cc https://github.com/epwalsh/obsidian.nvim/pull/778
> feat: add an UI option to ignore conceal warnings

- CHANGELOG.md
- lua/obsidian/commands/open.lua
- lua/obsidian/config.lua
- use `opts.open.func` to customize opening, fixes #164 and generalizes `open_app_foreground`
- deprecated `open_app_foreground`, and move `use_advanced_uri` to new module `open`
- fallback to just opening current vault if not in a note.
> `Obsidian open` refactor

- .github/workflows/main.yml
- CHANGELOG.md
- lua/obsidian/async.lua
- lua/obsidian/client.lua
- lua/obsidian/commands/check.lua
- lua/obsidian/note.lua
- lua/obsidian/path.lua
- lua/obsidian/search.lua
- lua/obsidian/ui.lua
- lua/obsidian/util.lua
- tests/helpers.lua
- tests/test_async.lua
- tests/test_client.lua
- tests/test_client_mini.lua
- tests/test_path.lua
- tests/test_search.lua
First step in removing plenary.
1. removed all `plenary.job` usage
Functionality impacted: find notes, backlinks, tags. **Try these out when reviewing this.**
2. removed `plenary.scandir` usage
- in `Path:rmtree`, not used anywhere except as a test helper
- in `search.find_notes_async`, literally not used anywhere in the code, but it has two tests lol. We shall write a pure lua version similar to this, not depending on `rg` or `plenary`, so this can be deleted as well.
- in `client:apply_async_raw`, it should be nicely replaced by `vim.fs.dir`, needs more test. It is only used by `Obsidian check` and result is now 30 times faster on my vault :)
3. removed `plenary.context_manager` uasge, sometime the code uses an `File` class that only runs in async context, some times uses the context …
> fix: remove `plenary.job` and `plenary.scandir`usage

- CHANGELOG.md
- lua/obsidian/templates.lua
- tests/test_templates.lua
Fixes #198
The indexes returned by `gfind()` are relative to the initial template string _**before**_ any substitutions take place. In the loop, however, we're using those same indexes to slice the string _**after**_ substitutions take place. As a consequence, the code keeps accumulating errors, unless the value happens to match the length of `{{var}}` _exactly_.
I've inlined the call to `string.find()` so that the indexes stay relative to the _current_ reference to `text`, rather than to the _initial_ reference to `text`. To make the diff as small as possible, I've changed the loop into a simple `while true` loop, but I'm open to ideas for a better implementation.
> fix(templates): text corrupted when custom variables appear more than once in a template file

- CHANGELOG.md
- README.md
- lua/obsidian/client.lua
- lua/obsidian/config.lua
- lua/obsidian/init.lua
> feat: separate user/internal config type, inline defaults

- CHANGELOG.md
- lua/obsidian/api.lua
Returns "unknown" commit hash instead of failing when git info is unavailable, fixing checkhealth functionality in environments like [nixvim](https://github.com/nix-community/nixvim).
This issue is mention in https://github.com/nix-community/nixvim/issues/3355.
```bash
==============================================================================
obsidian:                                                                 1 ❌
- ✅ OK neovim >= 0.11
obsidian.nvim [Version] ~
- ❌ ERROR Failed to run healthcheck for "obsidian" plugin. Exception:
...ovimPackages/start/obsidian.nvim/lua/obsidian/health.lua:0: attempt to index a nil value
```
```bash
==============================================================================
obsidian: …
```
> Handle error exit code from git in get_plugin_info

- CHANGELOG.md
- README.md
- lua/obsidian/api.lua
- lua/obsidian/builtin.lua
- lua/obsidian/commands/paste_img.lua
- lua/obsidian/config.lua
- tests/attachment/test_image.lua
resolves #119 and inspired by https://github.com/orgs/obsidian-nvim/discussions/265
There's now a 100% obsidian compatible default `img_text_func`, that formats differently depend on link style
```md
For markdown
For wiki
```
Then there's a new wiki page for configuring snacks to resolve image paths
https://github.com/obsidian-nvim/obsidian.nvim/wiki/Images
> feat: obsidian + snacks.image compatible img_text_func

- CHANGELOG.md
- lua/obsidian/note.lua
Fixes #279: add `check_buffers` option to `Note.write` and `Note.save` for automatically reloading buffers with `checktime` after writing them to disk
When enabled, `Note.save` checks if at least one buffer would be affected and, if so, then calls `checktime`. `Note.write` is just a wrapper around `Note.save`, so I've only changed it to forward the new option's value.
N/A
> feat: add `check_buffers` option to `Note.write` and `Note.save` for automatically reloading buffers with `checktime` after writing them to disk

- CHANGELOG.md
- lua/obsidian/note.lua
Stop false-pasitive invalid 'id' detection in frontmatter.
TODO Add screenshots to help explain your changes, if applicable.
> Fix false positive invalid id detection

- CHANGELOG.md
- lua/obsidian/daily/init.lua
Solves #290
Uses the `path:parent()` instead `opts.daily_note.folder` for the directory for daily notes. `opts.daily_note.folder` is already integrated into path from
> fix: respect subdirectories in date_format for daily files

- CHANGELOG.md
- lua/obsidian/api.lua
- lua/obsidian/util.lua
- tests/test_api.lua
only trigger in `paragraph` and `list` node
smart actions is now smarter :)
resolves #98
> checkbox with treesitter awareness

- CHANGELOG.md
- README.md
- lua/obsidian/api.lua
- lua/obsidian/commands/paste_img.lua
- lua/obsidian/config.lua
- lua/obsidian/img_paste.lua
resolves #315 
also moving towards `app.json` compatibility described in #72 
**TODO**
> feat: better attachment folder resolve

- CHANGELOG.md
- README.md
- lua/obsidian/config.lua
Config and README state this callback should receive 2 params (`client, workspace`), when in reality it only receives one.
> fix(#326): remove client param from post_set_workspace callback signature

- CHANGELOG.md
- lua/obsidian/pickers/_snacks.lua
> fix: `Snacks.picker` now follow `sort_by` and `sort_reversed` settings.

- CHANGELOG.md
- lua/obsidian/note.lua
resolves #352 
avoids loss of creation info, tags and etc, and don't eagerly update frontmatter until saving.
> fix: cache note as local var

- CHANGELOG.md
- lua/obsidian/commands/backlinks.lua
- lua/obsidian/commands/dailies.lua
- lua/obsidian/commands/links.lua
- lua/obsidian/commands/new_from_template.lua
- lua/obsidian/commands/tags.lua
- lua/obsidian/commands/template.lua
- lua/obsidian/commands/workspace.lua
- lua/obsidian/pickers/_fzf.lua
- lua/obsidian/pickers/_mini.lua
- lua/obsidian/pickers/_snacks.lua
- lua/obsidian/pickers/_telescope.lua
- lua/obsidian/pickers/picker.lua
pickers are historically contributed by different people, the logic is messy. This will enable the simplification of LSP code.
> picker cleanups

- CHANGELOG.md
- README.md
- lua/obsidian/api.lua
- lua/obsidian/init.lua
fold is not very in scope for now, but it causes a lot of bugs, we just guide users to setup fold in https://github.com/obsidian-nvim/obsidian.nvim/wiki/Folding
and if they have sensible fold options, trigger `za` in `smart_action`.
> Remove custom fold options

- CHANGELOG.md
- lua/obsidian/commands/toc.lua
- lua/obsidian/lsp/handlers.lua
- lua/obsidian/lsp/handlers/document_symbol.lua
- lua/obsidian/lsp/handlers/initialize.lua
- lua/obsidian/pickers/_fzf.lua
- lua/obsidian/pickers/_mini.lua
- lua/obsidian/pickers/_snacks.lua
- lua/obsidian/pickers/_telescope.lua
- lua/obsidian/pickers/picker.lua
- as titled
- also adds `format_item` callback to picker:pick, so cleaner display.
> feat: `documentSymbol` based toc.
